# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a
android.nonTransitiveRClass=false
# 禁用新架构以避免CMake配置问题
newArchEnabled=false
# 启用 Hermes 引擎
hermesEnabled=true
# 解决仓库配置冲突警告
android.disableAutomaticComponentCreation=true
# Kotlin
kotlin.code.style=official
android.enableJetifier=true
