/**
 * 路由地址常量类
 */
export class RouterUrl{

  /**
   * 首页Tab页面
   */
  static readonly MAIN_PAGE_URL = "mainPage"

  static readonly ONE_TAB_INDEX_PAGE: string = 'one/indexPage';

  static readonly TWO_TAB_INDEX_PAGE: string = 'two/indexPage';

  static readonly THREE_TAB_INDEX_PAGE: string = 'three/indexPage';

  static readonly FOUR_TAB_INDEX_PAGE: string = 'four/indexPage';

  /**
   * 通用Web页面容器的路由地址
   */
  static readonly WEB_PAGE_URL: string = 'common/webPage';

  static readonly TEST_PAGE_URL: string = 'common/testPage';

  /**
   * RN页面路由地址
   */
  static readonly RN_PAGE_URL: string = 'common/rnPage';

}